version: '2'
services:
    go-shortener:
        # build: .
        image: golang:1.8-alpine
        volumes:
            - .:/go/src/go-url-shortener
        working_dir: /go/src/go-url-shortener
        command: go run main.go
        ports:
            - "8080:8080"
        links:
            - redis
        environment:
            REDIS_URL: redis:6379

    redis:
        image: "redis:alpine"