version: '2'
services:
    go-shortener:
        build: .
        image: go-shortener
        ports:
            - "8080:8080"
        links:
            - redis
        environment:
            REDIS_URL: redis:6379
    redis:
        image: "redis:alpine"